# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: vmserver
output: server.gen.go
generate:
  models: true
  std-http-server: true
  strict-server: true
  embedded-spec: true
import-mapping:
  types.yml: github.com/krelinga/video-manager-api/go/vmapi
